### ISSUE TITLE
UnicodeDecodeError - Windows 7

### ISSUE THREAD

**Issue by Vaniax** [strycore/fakegir#10]
Hi, 

when I try to use the script with Windows 7 and Python3 I get:

```
Traceback (most recent call last):
  File "D:\fakegir.py", line 231, in <module>
    generate_fakegir()
  File "D:\fakegir.py", line 223, in generate_fakegir
    fakegir_content = parse_gir(gir_path)
  File "D:\fakegir.py", line 189, in parse_gir
    content = open(gir_path).read()
  File "D:\Programmierung\Python\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 684559: character maps to <undefined>
```

I installed PyGObject with the official Windows installer (https://wiki.gnome.org/Projects/PyGObject). What is the problem here?

**Comment by kastixx** [comment]
Vaniax, is this issue still actual?

If it is, could you try doing this:
```
git fetch
git checkout test-issue21
```
and running `fakegir.py` again?

It may be related to #21.

**Comment by kastixx** [comment]
Update: no need to switch branches, the patch is already merged to master.
